{
    "name": "Employee Target Summary Report",
    "version": "1.0",
    "author": "Darmawan Fatriananda",
    "category": "Rekapitulasi /Rekap Per OPD / Rekapitulasi Per Pegawai",
    "description": "Laporan Data Pegawai Yang Belum Membuat Target Dan Belum Aktifasi.",
    "website" : "www.asdarfat.wordpress.com",
    "license" : "",
    "depends": ['base','project','hr'],
    "init_xml": [],
    'update_xml': ["employee_target_summary_report.xml",],
    'demo_xml': [],
    'installable': True,
    'active': False,
}
